<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Additional Data' => 'Доп. информация',
    'Available Model list' => 'Классы моделей для протоколирования (с новой строчки)',
    'Cms Changelog' => 'Протокол изменений',
    'Cms changelog' => 'Протокол изменений',
    'Cms changelog protocol' => 'Протокол изменений',
    'Delete' => 'Удалили',
    'Event' => 'Событие',
    'Insert' => 'Добавили',
    'Ip' => 'IP адресс',
    'Model Class' => 'Класс модели',
    'Model Pk' => 'ID записи',
    'Name' => 'Название',
    'Operation Type' => 'Действие',
    'Setting' => 'Настройки',
    'Time' => 'Время',
    'Update' => 'Обновили',
    'User Agent' => 'User Agent',
    'User Id' => 'User Id',
    'Username' => 'Ник пользователя',
];
